version: 2

updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    reviewers:
      - "mrhallak"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: weekly
