name: CI/CD

on: 
  pull_request:
    branches:
      - master
      - dev

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Set up Python {{ cookiecutter.python_version }}
        uses: actions/setup-python@master
        with:
          python-version: {{ cookiecutter.python_version }}
      - name: Install black
        run: |
          pip install black

      - name: Check formatting with black
        run: |
          black --check {{ cookiecutter.project_name }}

      - name: Run tests
        run: |
          pytest
