version: 2

updates:
  - package-ecosystem: pip
    directory: "/requirements"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    target-branch: dev
    reviewers:
      - {{ cookiecutter.github_username }}
    allow:
      - dependency-type: direct
      - dependency-type: indirect
